


#spring:
#  datasource:
#   url: jdbc:h2:mem:testdb
#   username: sa
#  jpa: 
#    hibernate: 
#      ddl-auto: update
spring:
  datasource:
    generate-unique-name: false
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
